#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Save list of staged files before formatting
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|tsx|jsx|json|md)$')

# Run Biome formatter with --staged
pnpm biome check --write --staged

# Restage only the files you just formatted
echo "$STAGED_FILES" | xargs git add

echo "Pre-commit Biome formatting completed."